version: "3.4"

networks:
  mbase:
    driver: bridge

volumes:
  redis-data:
    driver: local

services:
  mbase:
    container_name: mbase
    image: mbase
    networks:
      - mbase
    depends_on:
      mbase-redis:
        condition: service_healthy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./static:/app/static
    env_file:
      - .env

  mbase-redis:
    container_name: mbase-redis
    image: docker.io/bitnami/redis:7.0
    networks:
      - mbase
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
