version: "3.4"

networks:
  mbase:
    driver: bridge

volumes:
  kafka:
  zookeeper_data:
  zookeeper_logs:

services:
  mbase:
    container_name: mbase
    image: mbase
    networks:
      - mbase
    depends_on:
      kafka:
        condition: service_healthy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./static:/app/static
    env_file:
      - .env

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.2
    networks:
      - mbase
    env_file:
      - .env
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log
    ports:
      - "22181:2181"
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.2
    networks:
      - mbase
    depends_on:
      zookeeper:
        condition: service_healthy
    restart: always
    volumes:
      - kafka:/var/lib/kafka/data
    ports:
      - "29092:29092"
      - "29101:29101"
    env_file:
      - .env
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 100
