version: "3.4"

networks:
  mbase:
    driver: bridge

volumes:
  redis-mbase-data:
    driver: local
  postgres-mbase-data:

services:
  mbase:
    container_name: mbase
    image: mbase
    networks:
      - mbase
    depends_on:
      mbase-redis:
        condition: service_healthy
      postgres-mbase:
        condition: service_healthy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./static:/app/static
    env_file:
      - .env

  mbase-redis:
    container_name: mbase-redis
    image: docker.io/bitnami/redis:7.0
    networks:
      - mbase
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-mbase-data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  postgres-mbase:
    container_name: postgres-mbase
    image: postgres:15
    networks:
      - mbase
    restart: always
    ports:
      - "5436:5432"
    volumes:
      - postgres-mbase-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mbase
      - POSTGRES_USER=mbase
      - POSTGRES_PASSWORD=mbase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
