version: "3.4"

services:
  mbase:
    container_name: mbase
    image: mbase
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./static:/app/static
    env_file:
      - .env
